### ISSUE TITLE
How to set default time range

### ISSUE THREAD

**Issue by YiniXu9506** [GopherJ/Vs#7]
Hi Cheng. I am wondering that can I set the default start time and end time at the very first rendering.  For example, I want the timeline displaying the experiments I ran last week. So that I can set the time range from `start_time_last_week` to `end_time_last_week`. 

Also, I want to support user to define the start time and end time by using date picker. 
![wechatimg67](https://user-images.githubusercontent.com/34967660/44309278-cd830c00-a3f6-11e8-819c-3f29b4c1840e.jpeg)

Does your component support this feature? Thank you!

**Comment by GopherJ** [comment]
No for now because d3Timeline will calculate the `startTIme` and `endTime` in `data`, and the time range will be `[startTime, endTime]`, when you change data, the range will be changed. If there is no data (data is a blank array), the default range is `[startOfYear, new Date()]`.

I think that you want is to be able to change the display area ? If it's that, I can add this feature later.

**Comment by YiniXu9506** [comment]
Yes. Exactly! What I want is user can set the display area by picking the dates they want. It will be great If you have time to add it as soon as possible. Thanks again!
